### PR TITLE
Add page entry

### LINKED ISSUE #36: Auto reload extension pages (popup)
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS:
  - Browser:
  - Library Version:

**I'm going to open a PR:**
  - [x] yes
  - [ ] no

**Description:**
I need the plugin to reload extension pages like the popup and not have the entire extension reload if the only entry point to change is in an extension page.

I don't think there is going to be a reliable way to auto-detect extension page entry points from the manifest so it will only be supported through `entries.extensionPage` or the CLI.

### PR DESCRIPTION
**Pull request by Kadauchi**
Extension pages can now be reloaded independently of the extension on changes. Closes #36

### CODE REVIEW

**Comment by dnmd** [comment]
@rubenspgcavalcante are there any plans to merge this PR? It is such a great package, with this addition things are even better.

**Comment by VasilyShelkov** [comment]
I haven't tested it, but it looks like it would close https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/15 as well :)

**Comment by rubenspgcavalcante** [comment]
Hey really sorry for the loooooong wait. I'm with some deadlines at work and bursting my time (and brain) focusing only on work. I'll test and if it's all fine I'll release a new minor version

**Comment by NickolasBoyer** [comment]
@Kadauchi what exactly does:
```
extensionPage: 'popup',
```
refer to? It's not a file path like the others, is it meant to?

**Comment by VasilyShelkov** [comment]
@NickolasBoyer, someone can correct me, but I believe it refers to the Webpack entry point key in the config not a file path

**Comment by Kadauchi** [comment]
@NickolasBoyer whoops, I see my mistake that caused the confusion.

The webpack entry
```
      popup: 'popup',
```
should be a filepath like
```
      popup: './my-popup-script.js',
```

The reloader options `entries.extensionPage` does correctly refer to the webpack entry like @VasilyShelkov mentioned.

**Comment by franciscolourenco** [comment]
I'm testing this feature with a options page, but am confused about the functionality it is supposed to provide.

I get the following logs in the console after making changes:

image

However the page stays the same.

Is this option supposed to automatically update the page to reflect changes to extension pages without having to reload the page?

**Comment by franciscolourenco** [comment]
I get it now, the `extensionPage` option only works when the `reloadPage` is set to `true`.
With `reloadPage: false` it doesn't do anything. However this option should be independent from the `extensionPage` page option. The later should only apply to content scripts.

**Pull request merged**
